/*
 * Shutterstock API Explorer
 * The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.
 *
 * The version of the OpenAPI document: 1.1.32
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.CatalogCollectionItemAsset;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CatalogCollectionItem
 */
public class CatalogCollectionItemTest {
    private final CatalogCollectionItem model = new CatalogCollectionItem();

    /**
     * Model tests for CatalogCollectionItem
     */
    @Test
    public void testCatalogCollectionItem() {
        // TODO: test CatalogCollectionItem
    }

    /**
     * Test the property 'asset'
     */
    @Test
    public void assetTest() {
        // TODO: test asset
    }

    /**
     * Test the property 'collectionIds'
     */
    @Test
    public void collectionIdsTest() {
        // TODO: test collectionIds
    }

    /**
     * Test the property 'createdTime'
     */
    @Test
    public void createdTimeTest() {
        // TODO: test createdTime
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

}
