/*
 * Shutterstock API Explorer
 * The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.
 *
 * The version of the OpenAPI document: 1.1.32
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CollectionItem
 */
public class CollectionItemTest {
    private final CollectionItem model = new CollectionItem();

    /**
     * Model tests for CollectionItem
     */
    @Test
    public void testCollectionItem() {
        // TODO: test CollectionItem
    }

    /**
     * Test the property 'addedTime'
     */
    @Test
    public void addedTimeTest() {
        // TODO: test addedTime
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'mediaType'
     */
    @Test
    public void mediaTypeTest() {
        // TODO: test mediaType
    }

}
