/*
 * Shutterstock API Explorer
 * The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.
 *
 * The version of the OpenAPI document: 1.1.32
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.Bands;
import com.konfigthis.client.model.Instruments;
import com.konfigthis.client.model.Preview;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for Descriptors
 */
public class DescriptorsTest {
    private final Descriptors model = new Descriptors();

    /**
     * Model tests for Descriptors
     */
    @Test
    public void testDescriptors() {
        // TODO: test Descriptors
    }

    /**
     * Test the property 'tags'
     */
    @Test
    public void tagsTest() {
        // TODO: test tags
    }

    /**
     * Test the property 'averageRenderSpeed'
     */
    @Test
    public void averageRenderSpeedTest() {
        // TODO: test averageRenderSpeed
    }

    /**
     * Test the property 'bands'
     */
    @Test
    public void bandsTest() {
        // TODO: test bands
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'instruments'
     */
    @Test
    public void instrumentsTest() {
        // TODO: test instruments
    }

    /**
     * Test the property 'maxTempo'
     */
    @Test
    public void maxTempoTest() {
        // TODO: test maxTempo
    }

    /**
     * Test the property 'minTempo'
     */
    @Test
    public void minTempoTest() {
        // TODO: test minTempo
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'previews'
     */
    @Test
    public void previewsTest() {
        // TODO: test previews
    }

}
