/*
 * Shutterstock API Explorer
 * The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.
 *
 * The version of the OpenAPI document: 1.1.32
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.ImageSizeDetails;
import com.konfigthis.client.model.Thumbnail;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ImageAssets
 */
public class ImageAssetsTest {
    private final ImageAssets model = new ImageAssets();

    /**
     * Model tests for ImageAssets
     */
    @Test
    public void testImageAssets() {
        // TODO: test ImageAssets
    }

    /**
     * Test the property 'hugeJpg'
     */
    @Test
    public void hugeJpgTest() {
        // TODO: test hugeJpg
    }

    /**
     * Test the property 'hugeThumb'
     */
    @Test
    public void hugeThumbTest() {
        // TODO: test hugeThumb
    }

    /**
     * Test the property 'largeThumb'
     */
    @Test
    public void largeThumbTest() {
        // TODO: test largeThumb
    }

    /**
     * Test the property 'mediumJpg'
     */
    @Test
    public void mediumJpgTest() {
        // TODO: test mediumJpg
    }

    /**
     * Test the property 'preview'
     */
    @Test
    public void previewTest() {
        // TODO: test preview
    }

    /**
     * Test the property 'preview1000'
     */
    @Test
    public void preview1000Test() {
        // TODO: test preview1000
    }

    /**
     * Test the property 'preview1500'
     */
    @Test
    public void preview1500Test() {
        // TODO: test preview1500
    }

    /**
     * Test the property 'smallJpg'
     */
    @Test
    public void smallJpgTest() {
        // TODO: test smallJpg
    }

    /**
     * Test the property 'smallThumb'
     */
    @Test
    public void smallThumbTest() {
        // TODO: test smallThumb
    }

    /**
     * Test the property 'supersizeJpg'
     */
    @Test
    public void supersizeJpgTest() {
        // TODO: test supersizeJpg
    }

    /**
     * Test the property 'vectorEps'
     */
    @Test
    public void vectorEpsTest() {
        // TODO: test vectorEps
    }

}
