/*
 * Shutterstock API Explorer
 * The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.
 *
 * The version of the OpenAPI document: 1.1.32
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.Url;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for LicenseEditorialContentResult
 */
public class LicenseEditorialContentResultTest {
    private final LicenseEditorialContentResult model = new LicenseEditorialContentResult();

    /**
     * Model tests for LicenseEditorialContentResult
     */
    @Test
    public void testLicenseEditorialContentResult() {
        // TODO: test LicenseEditorialContentResult
    }

    /**
     * Test the property 'allotmentCharge'
     */
    @Test
    public void allotmentChargeTest() {
        // TODO: test allotmentCharge
    }

    /**
     * Test the property 'download'
     */
    @Test
    public void downloadTest() {
        // TODO: test download
    }

    /**
     * Test the property 'editorialId'
     */
    @Test
    public void editorialIdTest() {
        // TODO: test editorialId
    }

    /**
     * Test the property 'error'
     */
    @Test
    public void errorTest() {
        // TODO: test error
    }

}
