/*
 * Shutterstock API Explorer
 * The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.
 *
 * The version of the OpenAPI document: 1.1.32
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.AudioRenderTimelineSpanInstrumentGroupStatus;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * An instrument and the status objects that specify when that instrument plays
 */
@ApiModel(description = "An instrument and the status objects that specify when that instrument plays")@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class AudioRenderTimelineSpanInstrumentGroup {
  public static final String SERIALIZED_NAME_INSTRUMENT_GROUP = "instrument_group";
  @SerializedName(SERIALIZED_NAME_INSTRUMENT_GROUP)
  private String instrumentGroup;

  public static final String SERIALIZED_NAME_STATUSES = "statuses";
  @SerializedName(SERIALIZED_NAME_STATUSES)
  private List<AudioRenderTimelineSpanInstrumentGroupStatus> statuses = null;

  public AudioRenderTimelineSpanInstrumentGroup() {
  }

  public AudioRenderTimelineSpanInstrumentGroup instrumentGroup(String instrumentGroup) {
    
    
    
    
    this.instrumentGroup = instrumentGroup;
    return this;
  }

   /**
   * The instrument ID
   * @return instrumentGroup
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "bright_roomy_kit", required = true, value = "The instrument ID")

  public String getInstrumentGroup() {
    return instrumentGroup;
  }


  public void setInstrumentGroup(String instrumentGroup) {
    
    
    
    this.instrumentGroup = instrumentGroup;
  }


  public AudioRenderTimelineSpanInstrumentGroup statuses(List<AudioRenderTimelineSpanInstrumentGroupStatus> statuses) {
    
    
    
    
    this.statuses = statuses;
    return this;
  }

  public AudioRenderTimelineSpanInstrumentGroup addStatusesItem(AudioRenderTimelineSpanInstrumentGroupStatus statusesItem) {
    if (this.statuses == null) {
      this.statuses = new ArrayList<>();
    }
    this.statuses.add(statusesItem);
    return this;
  }

   /**
   * An array of status objects
   * @return statuses
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "An array of status objects")

  public List<AudioRenderTimelineSpanInstrumentGroupStatus> getStatuses() {
    return statuses;
  }


  public void setStatuses(List<AudioRenderTimelineSpanInstrumentGroupStatus> statuses) {
    
    
    
    this.statuses = statuses;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the AudioRenderTimelineSpanInstrumentGroup instance itself
   */
  public AudioRenderTimelineSpanInstrumentGroup putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AudioRenderTimelineSpanInstrumentGroup audioRenderTimelineSpanInstrumentGroup = (AudioRenderTimelineSpanInstrumentGroup) o;
    return Objects.equals(this.instrumentGroup, audioRenderTimelineSpanInstrumentGroup.instrumentGroup) &&
        Objects.equals(this.statuses, audioRenderTimelineSpanInstrumentGroup.statuses)&&
        Objects.equals(this.additionalProperties, audioRenderTimelineSpanInstrumentGroup.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(instrumentGroup, statuses, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AudioRenderTimelineSpanInstrumentGroup {\n");
    sb.append("    instrumentGroup: ").append(toIndentedString(instrumentGroup)).append("\n");
    sb.append("    statuses: ").append(toIndentedString(statuses)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("instrument_group");
    openapiFields.add("statuses");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("instrument_group");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to AudioRenderTimelineSpanInstrumentGroup
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!AudioRenderTimelineSpanInstrumentGroup.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in AudioRenderTimelineSpanInstrumentGroup is not found in the empty JSON string", AudioRenderTimelineSpanInstrumentGroup.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : AudioRenderTimelineSpanInstrumentGroup.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      if (!jsonObj.get("instrument_group").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `instrument_group` to be a primitive type in the JSON string but got `%s`", jsonObj.get("instrument_group").toString()));
      }
      if (jsonObj.get("statuses") != null && !jsonObj.get("statuses").isJsonNull()) {
        JsonArray jsonArraystatuses = jsonObj.getAsJsonArray("statuses");
        if (jsonArraystatuses != null) {
          // ensure the json data is an array
          if (!jsonObj.get("statuses").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `statuses` to be an array in the JSON string but got `%s`", jsonObj.get("statuses").toString()));
          }

          // validate the optional field `statuses` (array)
          for (int i = 0; i < jsonArraystatuses.size(); i++) {
            AudioRenderTimelineSpanInstrumentGroupStatus.validateJsonObject(jsonArraystatuses.get(i).getAsJsonObject());
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!AudioRenderTimelineSpanInstrumentGroup.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'AudioRenderTimelineSpanInstrumentGroup' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<AudioRenderTimelineSpanInstrumentGroup> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(AudioRenderTimelineSpanInstrumentGroup.class));

       return (TypeAdapter<T>) new TypeAdapter<AudioRenderTimelineSpanInstrumentGroup>() {
           @Override
           public void write(JsonWriter out, AudioRenderTimelineSpanInstrumentGroup value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public AudioRenderTimelineSpanInstrumentGroup read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             AudioRenderTimelineSpanInstrumentGroup instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of AudioRenderTimelineSpanInstrumentGroup given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of AudioRenderTimelineSpanInstrumentGroup
  * @throws IOException if the JSON string is invalid with respect to AudioRenderTimelineSpanInstrumentGroup
  */
  public static AudioRenderTimelineSpanInstrumentGroup fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, AudioRenderTimelineSpanInstrumentGroup.class);
  }

 /**
  * Convert an instance of AudioRenderTimelineSpanInstrumentGroup to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

