/*
 * Shutterstock API Explorer
 * The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.
 *
 * The version of the OpenAPI document: 1.1.32
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.CatalogCollectionRole;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * CatalogCollectionRoleAssignmentsRoles
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class CatalogCollectionRoleAssignmentsRoles {
  public static final String SERIALIZED_NAME_EDITORS = "editors";
  @SerializedName(SERIALIZED_NAME_EDITORS)
  private List<CatalogCollectionRole> editors = null;

  public static final String SERIALIZED_NAME_OWNERS = "owners";
  @SerializedName(SERIALIZED_NAME_OWNERS)
  private List<CatalogCollectionRole> owners = null;

  public static final String SERIALIZED_NAME_VIEWERS = "viewers";
  @SerializedName(SERIALIZED_NAME_VIEWERS)
  private List<CatalogCollectionRole> viewers = null;

  public CatalogCollectionRoleAssignmentsRoles() {
  }

  public CatalogCollectionRoleAssignmentsRoles editors(List<CatalogCollectionRole> editors) {
    
    
    
    
    this.editors = editors;
    return this;
  }

  public CatalogCollectionRoleAssignmentsRoles addEditorsItem(CatalogCollectionRole editorsItem) {
    if (this.editors == null) {
      this.editors = new ArrayList<>();
    }
    this.editors.add(editorsItem);
    return this;
  }

   /**
   * Get editors
   * @return editors
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<CatalogCollectionRole> getEditors() {
    return editors;
  }


  public void setEditors(List<CatalogCollectionRole> editors) {
    
    
    
    this.editors = editors;
  }


  public CatalogCollectionRoleAssignmentsRoles owners(List<CatalogCollectionRole> owners) {
    
    
    
    
    this.owners = owners;
    return this;
  }

  public CatalogCollectionRoleAssignmentsRoles addOwnersItem(CatalogCollectionRole ownersItem) {
    if (this.owners == null) {
      this.owners = new ArrayList<>();
    }
    this.owners.add(ownersItem);
    return this;
  }

   /**
   * Get owners
   * @return owners
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<CatalogCollectionRole> getOwners() {
    return owners;
  }


  public void setOwners(List<CatalogCollectionRole> owners) {
    
    
    
    this.owners = owners;
  }


  public CatalogCollectionRoleAssignmentsRoles viewers(List<CatalogCollectionRole> viewers) {
    
    
    
    
    this.viewers = viewers;
    return this;
  }

  public CatalogCollectionRoleAssignmentsRoles addViewersItem(CatalogCollectionRole viewersItem) {
    if (this.viewers == null) {
      this.viewers = new ArrayList<>();
    }
    this.viewers.add(viewersItem);
    return this;
  }

   /**
   * Get viewers
   * @return viewers
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<CatalogCollectionRole> getViewers() {
    return viewers;
  }


  public void setViewers(List<CatalogCollectionRole> viewers) {
    
    
    
    this.viewers = viewers;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the CatalogCollectionRoleAssignmentsRoles instance itself
   */
  public CatalogCollectionRoleAssignmentsRoles putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CatalogCollectionRoleAssignmentsRoles catalogCollectionRoleAssignmentsRoles = (CatalogCollectionRoleAssignmentsRoles) o;
    return Objects.equals(this.editors, catalogCollectionRoleAssignmentsRoles.editors) &&
        Objects.equals(this.owners, catalogCollectionRoleAssignmentsRoles.owners) &&
        Objects.equals(this.viewers, catalogCollectionRoleAssignmentsRoles.viewers)&&
        Objects.equals(this.additionalProperties, catalogCollectionRoleAssignmentsRoles.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(editors, owners, viewers, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CatalogCollectionRoleAssignmentsRoles {\n");
    sb.append("    editors: ").append(toIndentedString(editors)).append("\n");
    sb.append("    owners: ").append(toIndentedString(owners)).append("\n");
    sb.append("    viewers: ").append(toIndentedString(viewers)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("editors");
    openapiFields.add("owners");
    openapiFields.add("viewers");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to CatalogCollectionRoleAssignmentsRoles
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!CatalogCollectionRoleAssignmentsRoles.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in CatalogCollectionRoleAssignmentsRoles is not found in the empty JSON string", CatalogCollectionRoleAssignmentsRoles.openapiRequiredFields.toString()));
        }
      }
      if (jsonObj.get("editors") != null && !jsonObj.get("editors").isJsonNull()) {
        JsonArray jsonArrayeditors = jsonObj.getAsJsonArray("editors");
        if (jsonArrayeditors != null) {
          // ensure the json data is an array
          if (!jsonObj.get("editors").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `editors` to be an array in the JSON string but got `%s`", jsonObj.get("editors").toString()));
          }

          // validate the optional field `editors` (array)
          for (int i = 0; i < jsonArrayeditors.size(); i++) {
            CatalogCollectionRole.validateJsonObject(jsonArrayeditors.get(i).getAsJsonObject());
          };
        }
      }
      if (jsonObj.get("owners") != null && !jsonObj.get("owners").isJsonNull()) {
        JsonArray jsonArrayowners = jsonObj.getAsJsonArray("owners");
        if (jsonArrayowners != null) {
          // ensure the json data is an array
          if (!jsonObj.get("owners").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `owners` to be an array in the JSON string but got `%s`", jsonObj.get("owners").toString()));
          }

          // validate the optional field `owners` (array)
          for (int i = 0; i < jsonArrayowners.size(); i++) {
            CatalogCollectionRole.validateJsonObject(jsonArrayowners.get(i).getAsJsonObject());
          };
        }
      }
      if (jsonObj.get("viewers") != null && !jsonObj.get("viewers").isJsonNull()) {
        JsonArray jsonArrayviewers = jsonObj.getAsJsonArray("viewers");
        if (jsonArrayviewers != null) {
          // ensure the json data is an array
          if (!jsonObj.get("viewers").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `viewers` to be an array in the JSON string but got `%s`", jsonObj.get("viewers").toString()));
          }

          // validate the optional field `viewers` (array)
          for (int i = 0; i < jsonArrayviewers.size(); i++) {
            CatalogCollectionRole.validateJsonObject(jsonArrayviewers.get(i).getAsJsonObject());
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CatalogCollectionRoleAssignmentsRoles.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CatalogCollectionRoleAssignmentsRoles' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CatalogCollectionRoleAssignmentsRoles> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CatalogCollectionRoleAssignmentsRoles.class));

       return (TypeAdapter<T>) new TypeAdapter<CatalogCollectionRoleAssignmentsRoles>() {
           @Override
           public void write(JsonWriter out, CatalogCollectionRoleAssignmentsRoles value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public CatalogCollectionRoleAssignmentsRoles read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             CatalogCollectionRoleAssignmentsRoles instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of CatalogCollectionRoleAssignmentsRoles given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of CatalogCollectionRoleAssignmentsRoles
  * @throws IOException if the JSON string is invalid with respect to CatalogCollectionRoleAssignmentsRoles
  */
  public static CatalogCollectionRoleAssignmentsRoles fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CatalogCollectionRoleAssignmentsRoles.class);
  }

 /**
  * Convert an instance of CatalogCollectionRoleAssignmentsRoles to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

