/*
 * Shutterstock API Explorer
 * The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.
 *
 * The version of the OpenAPI document: 1.1.32
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.EditorialCoverItem;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * Metadata about editorial livefeed
 */
@ApiModel(description = "Metadata about editorial livefeed")@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class EditorialImageLivefeed {
  public static final String SERIALIZED_NAME_COVER_ITEM = "cover_item";
  @SerializedName(SERIALIZED_NAME_COVER_ITEM)
  private EditorialCoverItem coverItem;

  public static final String SERIALIZED_NAME_CREATED_TIME = "created_time";
  @SerializedName(SERIALIZED_NAME_CREATED_TIME)
  private OffsetDateTime createdTime;

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_TOTAL_ITEM_COUNT = "total_item_count";
  @SerializedName(SERIALIZED_NAME_TOTAL_ITEM_COUNT)
  private Integer totalItemCount;

  public EditorialImageLivefeed() {
  }

  public EditorialImageLivefeed coverItem(EditorialCoverItem coverItem) {
    
    
    
    
    this.coverItem = coverItem;
    return this;
  }

   /**
   * Get coverItem
   * @return coverItem
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public EditorialCoverItem getCoverItem() {
    return coverItem;
  }


  public void setCoverItem(EditorialCoverItem coverItem) {
    
    
    
    this.coverItem = coverItem;
  }


  public EditorialImageLivefeed createdTime(OffsetDateTime createdTime) {
    
    
    
    
    this.createdTime = createdTime;
    return this;
  }

   /**
   * When the livefeed was initially created
   * @return createdTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "2018-07-17T12:42:03Z", value = "When the livefeed was initially created")

  public OffsetDateTime getCreatedTime() {
    return createdTime;
  }


  public void setCreatedTime(OffsetDateTime createdTime) {
    
    
    
    this.createdTime = createdTime;
  }


  public EditorialImageLivefeed id(String id) {
    
    
    
    
    this.id = id;
    return this;
  }

   /**
   * Livefeed ID
   * @return id
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "2018%2F07%2F17%2FPrince%20Charles%20and%20Camilla%20Duchess%20of%20Cornwall%20visit%20to%20Cornwall%2C%20Day%202", required = true, value = "Livefeed ID")

  public String getId() {
    return id;
  }


  public void setId(String id) {
    
    
    
    this.id = id;
  }


  public EditorialImageLivefeed name(String name) {
    
    
    
    
    this.name = name;
    return this;
  }

   /**
   * Name of the livefeed
   * @return name
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "Prince Charles and Camilla Duchess of Cornwall visit to Cornwall, Day 2", required = true, value = "Name of the livefeed")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    
    
    
    this.name = name;
  }


  public EditorialImageLivefeed totalItemCount(Integer totalItemCount) {
    
    
    
    
    this.totalItemCount = totalItemCount;
    return this;
  }

   /**
   * Total count of items in the livefeed
   * @return totalItemCount
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "38", required = true, value = "Total count of items in the livefeed")

  public Integer getTotalItemCount() {
    return totalItemCount;
  }


  public void setTotalItemCount(Integer totalItemCount) {
    
    
    
    this.totalItemCount = totalItemCount;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the EditorialImageLivefeed instance itself
   */
  public EditorialImageLivefeed putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EditorialImageLivefeed editorialImageLivefeed = (EditorialImageLivefeed) o;
    return Objects.equals(this.coverItem, editorialImageLivefeed.coverItem) &&
        Objects.equals(this.createdTime, editorialImageLivefeed.createdTime) &&
        Objects.equals(this.id, editorialImageLivefeed.id) &&
        Objects.equals(this.name, editorialImageLivefeed.name) &&
        Objects.equals(this.totalItemCount, editorialImageLivefeed.totalItemCount)&&
        Objects.equals(this.additionalProperties, editorialImageLivefeed.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(coverItem, createdTime, id, name, totalItemCount, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EditorialImageLivefeed {\n");
    sb.append("    coverItem: ").append(toIndentedString(coverItem)).append("\n");
    sb.append("    createdTime: ").append(toIndentedString(createdTime)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    totalItemCount: ").append(toIndentedString(totalItemCount)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("cover_item");
    openapiFields.add("created_time");
    openapiFields.add("id");
    openapiFields.add("name");
    openapiFields.add("total_item_count");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("id");
    openapiRequiredFields.add("name");
    openapiRequiredFields.add("total_item_count");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to EditorialImageLivefeed
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!EditorialImageLivefeed.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in EditorialImageLivefeed is not found in the empty JSON string", EditorialImageLivefeed.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : EditorialImageLivefeed.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      // validate the optional field `cover_item`
      if (jsonObj.get("cover_item") != null && !jsonObj.get("cover_item").isJsonNull()) {
        EditorialCoverItem.validateJsonObject(jsonObj.getAsJsonObject("cover_item"));
      }
      if (!jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      if (!jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!EditorialImageLivefeed.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'EditorialImageLivefeed' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<EditorialImageLivefeed> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(EditorialImageLivefeed.class));

       return (TypeAdapter<T>) new TypeAdapter<EditorialImageLivefeed>() {
           @Override
           public void write(JsonWriter out, EditorialImageLivefeed value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public EditorialImageLivefeed read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             EditorialImageLivefeed instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of EditorialImageLivefeed given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of EditorialImageLivefeed
  * @throws IOException if the JSON string is invalid with respect to EditorialImageLivefeed
  */
  public static EditorialImageLivefeed fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, EditorialImageLivefeed.class);
  }

 /**
  * Convert an instance of EditorialImageLivefeed to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

