/*
 * Shutterstock API Explorer
 * The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.
 *
 * The version of the OpenAPI document: 1.1.32
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.Image;
import com.konfigthis.client.model.Insights;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * Image search results
 */
@ApiModel(description = "Image search results")@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class ImageSearchResults {
  public static final String SERIALIZED_NAME_DATA = "data";
  @SerializedName(SERIALIZED_NAME_DATA)
  private List<Image> data = new ArrayList<>();

  public static final String SERIALIZED_NAME_INSIGHTS = "insights";
  @SerializedName(SERIALIZED_NAME_INSIGHTS)
  private Insights insights;

  public static final String SERIALIZED_NAME_MESSAGE = "message";
  @SerializedName(SERIALIZED_NAME_MESSAGE)
  private String message;

  public static final String SERIALIZED_NAME_PAGE = "page";
  @SerializedName(SERIALIZED_NAME_PAGE)
  private Integer page;

  public static final String SERIALIZED_NAME_PER_PAGE = "per_page";
  @SerializedName(SERIALIZED_NAME_PER_PAGE)
  private Integer perPage;

  public static final String SERIALIZED_NAME_SEARCH_ID = "search_id";
  @SerializedName(SERIALIZED_NAME_SEARCH_ID)
  private String searchId;

  public static final String SERIALIZED_NAME_SPELLCHECK_INFO = "spellcheck_info";
  @SerializedName(SERIALIZED_NAME_SPELLCHECK_INFO)
  private Object spellcheckInfo;

  public static final String SERIALIZED_NAME_TOTAL_COUNT = "total_count";
  @SerializedName(SERIALIZED_NAME_TOTAL_COUNT)
  private Integer totalCount;

  public ImageSearchResults() {
  }

  public ImageSearchResults data(List<Image> data) {
    
    
    
    
    this.data = data;
    return this;
  }

  public ImageSearchResults addDataItem(Image dataItem) {
    this.data.add(dataItem);
    return this;
  }

   /**
   * List of images
   * @return data
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "List of images")

  public List<Image> getData() {
    return data;
  }


  public void setData(List<Image> data) {
    
    
    
    this.data = data;
  }


  public ImageSearchResults insights(Insights insights) {
    
    
    
    
    this.insights = insights;
    return this;
  }

   /**
   * Get insights
   * @return insights
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Insights getInsights() {
    return insights;
  }


  public void setInsights(Insights insights) {
    
    
    
    this.insights = insights;
  }


  public ImageSearchResults message(String message) {
    
    
    
    
    this.message = message;
    return this;
  }

   /**
   * Server-generated message, if any
   * @return message
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Server-generated message, if any")

  public String getMessage() {
    return message;
  }


  public void setMessage(String message) {
    
    
    
    this.message = message;
  }


  public ImageSearchResults page(Integer page) {
    
    
    
    
    this.page = page;
    return this;
  }

   /**
   * Current page that is returned
   * @return page
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1", value = "Current page that is returned")

  public Integer getPage() {
    return page;
  }


  public void setPage(Integer page) {
    
    
    
    this.page = page;
  }


  public ImageSearchResults perPage(Integer perPage) {
    
    
    
    
    this.perPage = perPage;
    return this;
  }

   /**
   * Number of results per page
   * @return perPage
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "5", value = "Number of results per page")

  public Integer getPerPage() {
    return perPage;
  }


  public void setPerPage(Integer perPage) {
    
    
    
    this.perPage = perPage;
  }


  public ImageSearchResults searchId(String searchId) {
    
    
    
    
    this.searchId = searchId;
    return this;
  }

   /**
   * Unique identifier for the search request
   * @return searchId
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "749090bb-2967-4a20-b22e-c800dc845e10", required = true, value = "Unique identifier for the search request")

  public String getSearchId() {
    return searchId;
  }


  public void setSearchId(String searchId) {
    
    
    
    this.searchId = searchId;
  }


  public ImageSearchResults spellcheckInfo(Object spellcheckInfo) {
    
    
    
    
    this.spellcheckInfo = spellcheckInfo;
    return this;
  }

   /**
   * Returns information if search phrase has potentially been mistyped or another query would lead to better search results
   * @return spellcheckInfo
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Returns information if search phrase has potentially been mistyped or another query would lead to better search results")

  public Object getSpellcheckInfo() {
    return spellcheckInfo;
  }


  public void setSpellcheckInfo(Object spellcheckInfo) {
    
    
    
    this.spellcheckInfo = spellcheckInfo;
  }


  public ImageSearchResults totalCount(Integer totalCount) {
    
    
    
    
    this.totalCount = totalCount;
    return this;
  }

   /**
   * Total count of all results across all pages
   * @return totalCount
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "45", required = true, value = "Total count of all results across all pages")

  public Integer getTotalCount() {
    return totalCount;
  }


  public void setTotalCount(Integer totalCount) {
    
    
    
    this.totalCount = totalCount;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the ImageSearchResults instance itself
   */
  public ImageSearchResults putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ImageSearchResults imageSearchResults = (ImageSearchResults) o;
    return Objects.equals(this.data, imageSearchResults.data) &&
        Objects.equals(this.insights, imageSearchResults.insights) &&
        Objects.equals(this.message, imageSearchResults.message) &&
        Objects.equals(this.page, imageSearchResults.page) &&
        Objects.equals(this.perPage, imageSearchResults.perPage) &&
        Objects.equals(this.searchId, imageSearchResults.searchId) &&
        Objects.equals(this.spellcheckInfo, imageSearchResults.spellcheckInfo) &&
        Objects.equals(this.totalCount, imageSearchResults.totalCount)&&
        Objects.equals(this.additionalProperties, imageSearchResults.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(data, insights, message, page, perPage, searchId, spellcheckInfo, totalCount, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ImageSearchResults {\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("    insights: ").append(toIndentedString(insights)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    page: ").append(toIndentedString(page)).append("\n");
    sb.append("    perPage: ").append(toIndentedString(perPage)).append("\n");
    sb.append("    searchId: ").append(toIndentedString(searchId)).append("\n");
    sb.append("    spellcheckInfo: ").append(toIndentedString(spellcheckInfo)).append("\n");
    sb.append("    totalCount: ").append(toIndentedString(totalCount)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("data");
    openapiFields.add("insights");
    openapiFields.add("message");
    openapiFields.add("page");
    openapiFields.add("per_page");
    openapiFields.add("search_id");
    openapiFields.add("spellcheck_info");
    openapiFields.add("total_count");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("data");
    openapiRequiredFields.add("search_id");
    openapiRequiredFields.add("total_count");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to ImageSearchResults
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!ImageSearchResults.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ImageSearchResults is not found in the empty JSON string", ImageSearchResults.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : ImageSearchResults.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      // ensure the json data is an array
      if (!jsonObj.get("data").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `data` to be an array in the JSON string but got `%s`", jsonObj.get("data").toString()));
      }

      JsonArray jsonArraydata = jsonObj.getAsJsonArray("data");
      // validate the required field `data` (array)
      for (int i = 0; i < jsonArraydata.size(); i++) {
        Image.validateJsonObject(jsonArraydata.get(i).getAsJsonObject());
      };
      // validate the optional field `insights`
      if (jsonObj.get("insights") != null && !jsonObj.get("insights").isJsonNull()) {
        Insights.validateJsonObject(jsonObj.getAsJsonObject("insights"));
      }
      if ((jsonObj.get("message") != null && !jsonObj.get("message").isJsonNull()) && !jsonObj.get("message").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `message` to be a primitive type in the JSON string but got `%s`", jsonObj.get("message").toString()));
      }
      if (!jsonObj.get("search_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `search_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("search_id").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ImageSearchResults.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ImageSearchResults' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ImageSearchResults> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ImageSearchResults.class));

       return (TypeAdapter<T>) new TypeAdapter<ImageSearchResults>() {
           @Override
           public void write(JsonWriter out, ImageSearchResults value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public ImageSearchResults read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             ImageSearchResults instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of ImageSearchResults given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of ImageSearchResults
  * @throws IOException if the JSON string is invalid with respect to ImageSearchResults
  */
  public static ImageSearchResults fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ImageSearchResults.class);
  }

 /**
  * Convert an instance of ImageSearchResults to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

