/*
 * Shutterstock API Explorer
 * The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.
 *
 * The version of the OpenAPI document: 1.1.32
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.Cookie;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * Data required to redownload a video
 */
@ApiModel(description = "Data required to redownload a video")@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class RedownloadVideo {
  public static final String SERIALIZED_NAME_AUTH_COOKIE = "auth_cookie";
  @SerializedName(SERIALIZED_NAME_AUTH_COOKIE)
  private Cookie authCookie;

  public static final String SERIALIZED_NAME_SHOW_MODAL = "show_modal";
  @SerializedName(SERIALIZED_NAME_SHOW_MODAL)
  private Boolean showModal;

  /**
   * Size of the video
   */
  @JsonAdapter(SizeEnum.Adapter.class)
 public enum SizeEnum {
    WEB("web"),
    
    SD("sd"),
    
    HD("hd"),
    
    _4K("4k");

    private String value;

    SizeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static SizeEnum fromValue(String value) {
      for (SizeEnum b : SizeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<SizeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final SizeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public SizeEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return SizeEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_SIZE = "size";
  @SerializedName(SERIALIZED_NAME_SIZE)
  private SizeEnum size;

  public static final String SERIALIZED_NAME_VERIFICATION_CODE = "verification_code";
  @SerializedName(SERIALIZED_NAME_VERIFICATION_CODE)
  private String verificationCode;

  public RedownloadVideo() {
  }

  public RedownloadVideo authCookie(Cookie authCookie) {
    
    
    
    
    this.authCookie = authCookie;
    return this;
  }

   /**
   * Get authCookie
   * @return authCookie
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Cookie getAuthCookie() {
    return authCookie;
  }


  public void setAuthCookie(Cookie authCookie) {
    
    
    
    this.authCookie = authCookie;
  }


  public RedownloadVideo showModal(Boolean showModal) {
    
    
    
    
    this.showModal = showModal;
    return this;
  }

   /**
   * (Deprecated)
   * @return showModal
   * @deprecated
  **/
  @Deprecated
  @javax.annotation.Nullable
  @ApiModelProperty(value = "(Deprecated)")

  public Boolean getShowModal() {
    return showModal;
  }


  public void setShowModal(Boolean showModal) {
    
    
    
    this.showModal = showModal;
  }


  public RedownloadVideo size(SizeEnum size) {
    
    
    
    
    this.size = size;
    return this;
  }

   /**
   * Size of the video
   * @return size
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "WEB", value = "Size of the video")

  public SizeEnum getSize() {
    return size;
  }


  public void setSize(SizeEnum size) {
    
    
    
    this.size = size;
  }


  public RedownloadVideo verificationCode(String verificationCode) {
    
    
    
    
    this.verificationCode = verificationCode;
    return this;
  }

   /**
   * (Deprecated)
   * @return verificationCode
   * @deprecated
  **/
  @Deprecated
  @javax.annotation.Nullable
  @ApiModelProperty(value = "(Deprecated)")

  public String getVerificationCode() {
    return verificationCode;
  }


  public void setVerificationCode(String verificationCode) {
    
    
    
    this.verificationCode = verificationCode;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the RedownloadVideo instance itself
   */
  public RedownloadVideo putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RedownloadVideo redownloadVideo = (RedownloadVideo) o;
    return Objects.equals(this.authCookie, redownloadVideo.authCookie) &&
        Objects.equals(this.showModal, redownloadVideo.showModal) &&
        Objects.equals(this.size, redownloadVideo.size) &&
        Objects.equals(this.verificationCode, redownloadVideo.verificationCode)&&
        Objects.equals(this.additionalProperties, redownloadVideo.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(authCookie, showModal, size, verificationCode, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RedownloadVideo {\n");
    sb.append("    authCookie: ").append(toIndentedString(authCookie)).append("\n");
    sb.append("    showModal: ").append(toIndentedString(showModal)).append("\n");
    sb.append("    size: ").append(toIndentedString(size)).append("\n");
    sb.append("    verificationCode: ").append(toIndentedString(verificationCode)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("auth_cookie");
    openapiFields.add("show_modal");
    openapiFields.add("size");
    openapiFields.add("verification_code");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to RedownloadVideo
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!RedownloadVideo.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in RedownloadVideo is not found in the empty JSON string", RedownloadVideo.openapiRequiredFields.toString()));
        }
      }
      // validate the optional field `auth_cookie`
      if (jsonObj.get("auth_cookie") != null && !jsonObj.get("auth_cookie").isJsonNull()) {
        Cookie.validateJsonObject(jsonObj.getAsJsonObject("auth_cookie"));
      }
      if ((jsonObj.get("size") != null && !jsonObj.get("size").isJsonNull()) && !jsonObj.get("size").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `size` to be a primitive type in the JSON string but got `%s`", jsonObj.get("size").toString()));
      }
      if ((jsonObj.get("verification_code") != null && !jsonObj.get("verification_code").isJsonNull()) && !jsonObj.get("verification_code").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `verification_code` to be a primitive type in the JSON string but got `%s`", jsonObj.get("verification_code").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!RedownloadVideo.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'RedownloadVideo' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<RedownloadVideo> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(RedownloadVideo.class));

       return (TypeAdapter<T>) new TypeAdapter<RedownloadVideo>() {
           @Override
           public void write(JsonWriter out, RedownloadVideo value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public RedownloadVideo read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             RedownloadVideo instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of RedownloadVideo given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of RedownloadVideo
  * @throws IOException if the JSON string is invalid with respect to RedownloadVideo
  */
  public static RedownloadVideo fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, RedownloadVideo.class);
  }

 /**
  * Convert an instance of RedownloadVideo to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

