/*
 * Shutterstock API Explorer
 * The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.
 *
 * The version of the OpenAPI document: 1.1.32
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.model.BulkImageSearchResults;
import com.konfigthis.client.model.CategoryDataList;
import com.konfigthis.client.model.Collection;
import com.konfigthis.client.model.CollectionCreateRequest;
import com.konfigthis.client.model.CollectionCreateResponse;
import com.konfigthis.client.model.CollectionDataList;
import com.konfigthis.client.model.CollectionItem;
import com.konfigthis.client.model.CollectionItemDataList;
import com.konfigthis.client.model.CollectionItemRequest;
import com.konfigthis.client.model.CollectionUpdateRequest;
import com.konfigthis.client.model.Cookie;
import com.konfigthis.client.model.DownloadHistoryDataList;
import com.konfigthis.client.model.FeaturedCollection;
import com.konfigthis.client.model.FeaturedCollectionDataList;
import com.konfigthis.client.model.Image;
import com.konfigthis.client.model.ImageDataList;
import com.konfigthis.client.model.ImageSearchResults;
import com.konfigthis.client.model.Language;
import com.konfigthis.client.model.LicenseImageRequest;
import com.konfigthis.client.model.LicenseImageResultDataList;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import com.konfigthis.client.model.RecommendationDataList;
import com.konfigthis.client.model.RedownloadImage;
import com.konfigthis.client.model.SearchEntitiesRequest;
import com.konfigthis.client.model.SearchEntitiesResponse;
import com.konfigthis.client.model.SearchImage;
import com.konfigthis.client.model.Suggestions;
import com.konfigthis.client.model.UpdatedMediaDataList;
import com.konfigthis.client.model.Url;
import com.konfigthis.client.model.VLicenseImage;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ImagesApi
 */
@Disabled
public class ImagesApiTest {

    private static ImagesApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new ImagesApi(apiClient);
    }

    /**
     * Add images to collections
     *
     * This endpoint adds one or more images to a collection by image IDs.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void addToCollectionItemsTest() throws ApiException {
        List<CollectionItem> items = null;
        String id = null;
        api.addToCollectionItems(items, id)
                .execute();
        // TODO: test validations
    }

    /**
     * Create image collections
     *
     * This endpoint creates one or more image collections (lightboxes). To add images to the collections, use &#x60;POST /v2/images/collections/{id}/items&#x60;.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createCollectionTest() throws ApiException {
        String name = null;
        CollectionCreateResponse response = api.createCollection(name)
                .execute();
        // TODO: test validations
    }

    /**
     * Delete image collections
     *
     * This endpoint deletes an image collection.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteCollectionTest() throws ApiException {
        String id = null;
        api.deleteCollection(id)
                .execute();
        // TODO: test validations
    }

    /**
     * Get keywords from text
     *
     * This endpoint returns up to 10 important keywords from a block of plain text.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void extractKeywordsFromTextTest() throws ApiException {
        String text = null;
        SearchEntitiesResponse response = api.extractKeywordsFromText(text)
                .execute();
        // TODO: test validations
    }

    /**
     * Get the details of featured image collections
     *
     * This endpoint gets more detailed information about a featured collection, including its cover image and timestamps for its creation and most recent update. To get the images, use &#x60;GET /v2/images/collections/featured/{id}/items&#x60;.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void featuredCollectionDetailsTest() throws ApiException {
        String id = null;
        String embed = null;
        String assetHint = null;
        FeaturedCollection response = api.featuredCollectionDetails(id)
                .embed(embed)
                .assetHint(assetHint)
                .execute();
        // TODO: test validations
    }

    /**
     * Get the details of image collections
     *
     * This endpoint gets more detailed information about a collection, including its cover image and timestamps for its creation and most recent update. To get the images in collections, use &#x60;GET /v2/images/collections/{id}/items&#x60;.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getCollectionDetailsTest() throws ApiException {
        String id = null;
        List<String> embed = null;
        String shareCode = null;
        Collection response = api.getCollectionDetails(id)
                .embed(embed)
                .shareCode(shareCode)
                .execute();
        // TODO: test validations
    }

    /**
     * Get the contents of featured image collections
     *
     * This endpoint lists the IDs of images in a featured collection and the date that each was added.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getCollectionItemsTest() throws ApiException {
        String id = null;
        Integer page = null;
        Integer perPage = null;
        CollectionItemDataList response = api.getCollectionItems(id)
                .page(page)
                .perPage(perPage)
                .execute();
        // TODO: test validations
    }

    /**
     * Get the contents of image collections
     *
     * This endpoint lists the IDs of images in a collection and the date that each was added.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getCollectionItems_0Test() throws ApiException {
        String id = null;
        Integer page = null;
        Integer perPage = null;
        String shareCode = null;
        String sort = null;
        CollectionItemDataList response = api.getCollectionItems_0(id)
                .page(page)
                .perPage(perPage)
                .shareCode(shareCode)
                .sort(sort)
                .execute();
        // TODO: test validations
    }

    /**
     * Get details about images
     *
     * This endpoint shows information about an image, including a URL to a preview image and the sizes that it is available in.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getDetailsTest() throws ApiException {
        String id = null;
        Language language = null;
        String view = null;
        String searchId = null;
        Image response = api.getDetails(id)
                .language(language)
                .view(view)
                .searchId(searchId)
                .execute();
        // TODO: test validations
    }

    /**
     * Get suggestions for a search term
     *
     * This endpoint provides autocomplete suggestions for partial search terms.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getSearchSuggestionsTest() throws ApiException {
        String query = null;
        Integer limit = null;
        Suggestions response = api.getSearchSuggestions(query)
                .limit(limit)
                .execute();
        // TODO: test validations
    }

    /**
     * License images
     *
     * This endpoint gets licenses for one or more images. You must specify the image IDs in the body parameter and other details like the format, size, and subscription ID either in the query parameter or with each image ID in the body parameter. Values in the body parameter override values in the query parameters. The download links in the response are valid for 8 hours.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void licenseImagesForMultipleTest() throws ApiException {
        List<VLicenseImage> images = null;
        String subscriptionId = null;
        String format = null;
        String size = null;
        String searchId = null;
        LicenseImageResultDataList response = api.licenseImagesForMultiple(images)
                .subscriptionId(subscriptionId)
                .format(format)
                .size(size)
                .searchId(searchId)
                .execute();
        // TODO: test validations
    }

    /**
     * List image categories
     *
     * This endpoint lists the categories (Shutterstock-assigned genres) that images can belong to.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listCategoriesTest() throws ApiException {
        Language language = null;
        CategoryDataList response = api.listCategories()
                .language(language)
                .execute();
        // TODO: test validations
    }

    /**
     * List image collections
     *
     * This endpoint lists your collections of images and their basic attributes.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listCollectionsTest() throws ApiException {
        List<String> embed = null;
        Integer page = null;
        Integer perPage = null;
        CollectionDataList response = api.listCollections()
                .embed(embed)
                .page(page)
                .perPage(perPage)
                .execute();
        // TODO: test validations
    }

    /**
     * List featured image collections
     *
     * This endpoint lists featured collections of specific types and a name and cover image for each collection.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listFeaturedCollectionsTest() throws ApiException {
        String embed = null;
        List<String> type = null;
        String assetHint = null;
        FeaturedCollectionDataList response = api.listFeaturedCollections()
                .embed(embed)
                .type(type)
                .assetHint(assetHint)
                .execute();
        // TODO: test validations
    }

    /**
     * List images
     *
     * This endpoint lists information about one or more images, including the available sizes.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listInfoTest() throws ApiException {
        List<String> id = null;
        String view = null;
        String searchId = null;
        ImageDataList response = api.listInfo(id)
                .view(view)
                .searchId(searchId)
                .execute();
        // TODO: test validations
    }

    /**
     * List image licenses
     *
     * This endpoint lists existing licenses.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listLicensesTest() throws ApiException {
        String imageId = null;
        String license = null;
        Integer page = null;
        Integer perPage = null;
        String sort = null;
        String username = null;
        OffsetDateTime startDate = null;
        OffsetDateTime endDate = null;
        String downloadAvailability = null;
        Boolean teamHistory = null;
        DownloadHistoryDataList response = api.listLicenses()
                .imageId(imageId)
                .license(license)
                .page(page)
                .perPage(perPage)
                .sort(sort)
                .username(username)
                .startDate(startDate)
                .endDate(endDate)
                .downloadAvailability(downloadAvailability)
                .teamHistory(teamHistory)
                .execute();
        // TODO: test validations
    }

    /**
     * List recommended images
     *
     * This endpoint returns images that customers put in the same collection as the specified image IDs.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listRecommendedImagesTest() throws ApiException {
        List<String> id = null;
        Integer maxItems = null;
        Boolean safe = null;
        RecommendationDataList response = api.listRecommendedImages(id)
                .maxItems(maxItems)
                .safe(safe)
                .execute();
        // TODO: test validations
    }

    /**
     * List similar images
     *
     * This endpoint returns images that are visually similar to an image that you specify.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listSimilarImagesTest() throws ApiException {
        String id = null;
        Language language = null;
        Integer page = null;
        Integer perPage = null;
        String view = null;
        ImageSearchResults response = api.listSimilarImages(id)
                .language(language)
                .page(page)
                .perPage(perPage)
                .view(view)
                .execute();
        // TODO: test validations
    }

    /**
     * List updated images
     *
     * This endpoint lists images that have been updated in the specified time period to update content management systems (CMS) or digital asset management (DAM) systems. In most cases, use the &#x60;interval&#x60; parameter to show images that were updated recently, but you can also use the &#x60;start_date&#x60; and &#x60;end_date&#x60; parameters to specify a range of no more than three days. Do not use the &#x60;interval&#x60; parameter with either &#x60;start_date&#x60; or &#x60;end_date&#x60;.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listUpdatedContentTest() throws ApiException {
        List<String> type = null;
        LocalDate startDate = null;
        LocalDate endDate = null;
        String interval = null;
        Integer page = null;
        Integer perPage = null;
        String sort = null;
        UpdatedMediaDataList response = api.listUpdatedContent()
                .type(type)
                .startDate(startDate)
                .endDate(endDate)
                .interval(interval)
                .page(page)
                .perPage(perPage)
                .sort(sort)
                .execute();
        // TODO: test validations
    }

    /**
     * Download images
     *
     * This endpoint redownloads images that you have already received a license for. The download links in the response are valid for 8 hours.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void redownloadLicenseTest() throws ApiException {
        String id = null;
        Cookie authCookie = null;
        Boolean showModal = null;
        String size = null;
        String verificationCode = null;
        Url response = api.redownloadLicense(id)
                .authCookie(authCookie)
                .showModal(showModal)
                .size(size)
                .verificationCode(verificationCode)
                .execute();
        // TODO: test validations
    }

    /**
     * Remove images from collections
     *
     * This endpoint removes one or more images from a collection.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void removeFromCollectionTest() throws ApiException {
        String id = null;
        List<String> itemId = null;
        api.removeFromCollection(id)
                .itemId(itemId)
                .execute();
        // TODO: test validations
    }

    /**
     * Rename image collections
     *
     * This endpoint sets a new name for an image collection.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void renameCollectionTest() throws ApiException {
        String name = null;
        String id = null;
        api.renameCollection(name, id)
                .execute();
        // TODO: test validations
    }

    /**
     * Run multiple image searches
     *
     * This endpoint runs up to 5 image searches in a single request and returns up to 20 results per search. You can provide global search parameters in the query parameters and override them for each search in the body parameter. The query and body parameters are the same as in the &#x60;GET /v2/images/search&#x60; endpoint.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void runMultipleSearchesTest() throws ApiException {
        LocalDate addedDate = null;
        LocalDate addedDateStart = null;
        Double aspectRatioMin = null;
        Double aspectRatioMax = null;
        Double aspectRatio = null;
        LocalDate addedDateEnd = null;
        String category = null;
        String color = null;
        List<String> contributor = null;
        Object contributorCountry = null;
        String fields = null;
        Integer height = null;
        Integer heightFrom = null;
        Integer heightTo = null;
        List<String> imageType = null;
        Boolean keywordSafeSearch = null;
        Language language = null;
        List<String> license = null;
        List<String> model = null;
        String orientation = null;
        Integer page = null;
        Integer perPage = null;
        Boolean peopleModelReleased = null;
        String peopleAge = null;
        List<String> peopleEthnicity = null;
        String peopleGender = null;
        Integer peopleNumber = null;
        String region = null;
        Boolean safe = null;
        String sort = null;
        Boolean spellcheckQuery = null;
        String view = null;
        Integer width = null;
        Integer widthFrom = null;
        Integer widthTo = null;
        BulkImageSearchResults response = api.runMultipleSearches()
                .addedDate(addedDate)
                .addedDateStart(addedDateStart)
                .aspectRatioMin(aspectRatioMin)
                .aspectRatioMax(aspectRatioMax)
                .aspectRatio(aspectRatio)
                .addedDateEnd(addedDateEnd)
                .category(category)
                .color(color)
                .contributor(contributor)
                .contributorCountry(contributorCountry)
                .fields(fields)
                .height(height)
                .heightFrom(heightFrom)
                .heightTo(heightTo)
                .imageType(imageType)
                .keywordSafeSearch(keywordSafeSearch)
                .language(language)
                .license(license)
                .model(model)
                .orientation(orientation)
                .page(page)
                .perPage(perPage)
                .peopleModelReleased(peopleModelReleased)
                .peopleAge(peopleAge)
                .peopleEthnicity(peopleEthnicity)
                .peopleGender(peopleGender)
                .peopleNumber(peopleNumber)
                .region(region)
                .safe(safe)
                .sort(sort)
                .spellcheckQuery(spellcheckQuery)
                .view(view)
                .width(width)
                .widthFrom(widthFrom)
                .widthTo(widthTo)
                .execute();
        // TODO: test validations
    }

    /**
     * Search for images
     *
     * This endpoint searches for images. If you specify more than one search parameter, the API uses an AND condition. Array parameters can be specified multiple times; in this case, the API uses an AND or an OR condition with those values, depending on the parameter. You can also filter search terms out in the &#x60;query&#x60; parameter by prefixing the term with NOT. Free API accounts show results only from a limited library of media, not the full Shutterstock media library. Also, the number of search fields they can use in a request is limited.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void searchImagesTest() throws ApiException {
        LocalDate addedDate = null;
        LocalDate addedDateStart = null;
        Double aspectRatioMin = null;
        Double aspectRatioMax = null;
        Double aspectRatio = null;
        Boolean aiSearch = null;
        Integer aiLabelsLimit = null;
        String aiIndustry = null;
        String aiObjective = null;
        LocalDate addedDateEnd = null;
        String category = null;
        String color = null;
        List<String> contributor = null;
        Object contributorCountry = null;
        String fields = null;
        Integer height = null;
        Integer heightFrom = null;
        Integer heightTo = null;
        List<String> imageType = null;
        Boolean keywordSafeSearch = null;
        Language language = null;
        List<String> license = null;
        List<String> model = null;
        String orientation = null;
        Integer page = null;
        Integer perPage = null;
        Boolean peopleModelReleased = null;
        String peopleAge = null;
        List<String> peopleEthnicity = null;
        String peopleGender = null;
        Integer peopleNumber = null;
        String query = null;
        String region = null;
        Boolean safe = null;
        String sort = null;
        Boolean spellcheckQuery = null;
        String view = null;
        Integer width = null;
        Integer widthFrom = null;
        Integer widthTo = null;
        ImageSearchResults response = api.searchImages()
                .addedDate(addedDate)
                .addedDateStart(addedDateStart)
                .aspectRatioMin(aspectRatioMin)
                .aspectRatioMax(aspectRatioMax)
                .aspectRatio(aspectRatio)
                .aiSearch(aiSearch)
                .aiLabelsLimit(aiLabelsLimit)
                .aiIndustry(aiIndustry)
                .aiObjective(aiObjective)
                .addedDateEnd(addedDateEnd)
                .category(category)
                .color(color)
                .contributor(contributor)
                .contributorCountry(contributorCountry)
                .fields(fields)
                .height(height)
                .heightFrom(heightFrom)
                .heightTo(heightTo)
                .imageType(imageType)
                .keywordSafeSearch(keywordSafeSearch)
                .language(language)
                .license(license)
                .model(model)
                .orientation(orientation)
                .page(page)
                .perPage(perPage)
                .peopleModelReleased(peopleModelReleased)
                .peopleAge(peopleAge)
                .peopleEthnicity(peopleEthnicity)
                .peopleGender(peopleGender)
                .peopleNumber(peopleNumber)
                .query(query)
                .region(region)
                .safe(safe)
                .sort(sort)
                .spellcheckQuery(spellcheckQuery)
                .view(view)
                .width(width)
                .widthFrom(widthFrom)
                .widthTo(widthTo)
                .execute();
        // TODO: test validations
    }

}
